
<html>
<head>
<script>
var element=document.getElementById;

function startUp()
{
if(top == self)
{
	document.getElementById("pophead").style.display='none';
}
	else
		{
			document.getElementById("pophead").style.display='block';
		}
}

function menuChoiceSet(p, menu)
{
	parent.parent.menuChoice(p, menu);
}

function doPopup(t,p)
{
parent.parent.menuChoiceClick(t, p);
}
</script>

<title>Reman, Core, Logistics and Inventory Management</title>

<body onLoad="startUp()" leftmargin=0 topmargin=0 scroll='auto'>
<link rel="stylesheet" type="text/css" href="css/primaryClass.css"> 

		<center><img src='images/blank.gif' width=1 height=7></center>
		<center><table width='100%' cellpadding=1 cellspacing=1 border=0 class='slideBlendTop' height=60>
		<tr>
		<td width=48>
			<center><img src='images/menus.png'></center>
		</td>
		<td class='fontClass14' style='color:#FFFFFF; padding:0px 10px;' align='left'>
		Reman, Core, Logistics and Inventory Management
		</td>
		<td width='20'>
		<center><img src='images/blank.gif' width=20 height=30></center>
		</td>
		<td width=100 id='pophead' style="display='block'">
			<div align='left'><table width='100' cellpadding=0 cellspacing=0 border=0>
			<tr>
			<td class='fontClass10' align='left' style='padding:0px 2px; color:#4fff4f;' onMouseOver="style.cursor='hand'" onClick="window.open('http://srcreclaim.com/main.php?')">
			BREAK&nbsp;OUT
			</td>
			<td>
			<center><img src='images/popout.png' onMouseOver="style.cursor='hand'" onClick="window.open('http://srcreclaim.com/main.php?')"></center>
			</td>
			<td width=1>
			<center><img src='images/blank.gif' width=20 height=1></center>
			</td>
			</tr>
			</table></div>
		</td>
		</tr>
		</table></center>

<div align='left'><table width='100%' cellpadding=0 cellspacing=0 border=0>
<tr>
<td width=10>
<center><img src='images/blank.gif' width=20 height=30></center>
</td>
<td>
<div align='left'><table cellpadding=2 cellspacing=2 border=0>
<tr>
<td colSpan=3>
<div align='left'><table cellpadding=0 cellspacing=0 border=0 width='755'>
<tr>
<td>
<center><img src='logos/emdLogo2.png'></center></td>
<td>
<center><img src='images/blank.gif' width=100 height=1></center>
</td>
<td vAlign='bottom'>

<div align='right'><table cellpadding=0 cellspacing=0 border=0>
<tr>
<td vAlign='middle'>
	<div align='right'><img src='images/settings60.png'></div>
</td>
<td vAlign='bottom'>
<center><img src='images/blank.gif' width=1 height=19></center>
<div align='right'><table cellpadding=0 cellspacing=2 border=0 style="background:#424242; border:0px solid; border-color:#424242;" width=370>
<tr><td width='20%' class='fontClass8' align='right' style='padding:0px 2px; border:1px solid; border-color:#CCCCCC; background:#FFFFFF; color:#424242;'>User&nbsp;ID</td><td width='30%' class='fontClass8' align='left' style='padding:0px 2px; border:0px solid; border-color:#424242; color:#336699; background:#336699; color:#FFFFFF;'>248</td><td width='20%' class='fontClass8' align='right' style='padding:0px 2px; border:1px solid; border-color:#CCCCCC; background:#FFFFFF; color:#424242;'>First&nbsp;Name</td><td width='30%' class='fontClass8' align='left' style='padding:0px 2px; border:0px solid; border-color:#424242; color:#336699; background:#336699; color:#FFFFFF;'>Dustin</td></tr><tr><td width='20%' class='fontClass8' align='right' style='padding:0px 2px; border:1px solid; border-color:#CCCCCC; background:#FFFFFF; color:#424242;'>Last&nbsp;Name</td><td width='30%' class='fontClass8' align='left' style='padding:0px 2px; border:0px solid; border-color:#424242; color:#336699; background:#336699; color:#FFFFFF;'>Riggs</td><td width='20%' class='fontClass8' align='right' style='padding:0px 2px; border:1px solid; border-color:#CCCCCC; background:#FFFFFF; color:#424242;'>Current&nbsp;Partner</td><td width='30%' class='fontClass8' align='left' style='padding:0px 2px; border:0px solid; border-color:#424242; color:#336699; background:#336699; color:#FFFFFF;'>EMD</td></tr><tr><td width='20%' class='fontClass8' align='right' style='padding:0px 2px; border:1px solid; border-color:#CCCCCC; background:#FFFFFF; color:#424242;'>Zone</td><td width='30%' class='fontClass8' align='left' style='padding:0px 2px; border:0px solid; border-color:#424242; color:#336699; background:#336699; color:#FFFFFF;'>13</td><td width='20%' class='fontClass8' align='right' style='padding:0px 2px; border:1px solid; border-color:#CCCCCC; background:#FFFFFF; color:#424242;'>User&nbsp;Name</td><td width='30%' class='fontClass8' align='left' style='padding:0px 2px; border:0px solid; border-color:#424242; color:#336699; background:#336699; color:#FFFFFF;'>driggs
</td></tr></tr></table></div>
<center><img src='images/shadow.png' height=14 width=370></center>
</td>
</tr>
</table></div>
</td>
</tr>
<tr>
<td colSpan=5>
<div align='right'><table cellpadding=0 cellspacing=0 border=0>
<tr>
<td>
<div align='center'><table cellpadding=0 cellspacing=0 border=0 style='background:#D1E8F7'>
<tr>
<td rowSpan=2>
<center><img src='images/led_bluera.png' width=6 height=23></center>
</td>
<td class='fontClass8' align='left' style='padding:0px 2px; color:#000099;'>
OPEN&nbsp;ACCESS
</td>
</tr>
<tr>
<td class='fontClass8' align='left' style='padding:0px 2px; color:#000099;'>
NO&nbsp;RESTRICTIONS
</td>
</tr>
</table></div>	
</td>
<td>
<center><img src='images/blank.gif' width=20 height=1></center>
</td>
<td>
<div align='center'><table cellpadding=0 cellspacing=0 border=0 style='background:#FADEDB'>
<tr>
<td rowSpan=2>
<center><img src='images/led_red.png' width=6 height=23></center>
</td>
<td class='fontClass8' align='left' style='padding:0px 2px; color:#990000;'>
NO&nbsp;ACCESS
</td>
</tr>
<tr>
<td class='fontClass8' align='left' style='padding:0px 2px; color:#990000;'>
RESTRICTED&nbsp;ACCESS
</td>
</tr>
</table></div>	
</td>
<td>
<center><img src='images/blank.gif' width=20 height=1></center>
</td>
<td>
<div align='center'><table cellpadding=0 cellspacing=0 border=0 style='background:#E3FAE3'>
<tr>
<td rowSpan=2>
<center><img src='images/led_green.png' width=6 height=23></center>
</td>
<td class='fontClass8' align='left' style='padding:0px 2px; color:#009900;'>
ACCESS&nbsp;GRANTED
</td>
</tr>
<tr>
<td class='fontClass8' align='left' style='padding:0px 2px; color:#009900;'>
RESTRICTED&nbsp;ACCESS
</td>
</tr>
</table></div>	
</td>
<td>
<center><img src='images/blank.gif' width=2 height=1></center>
</td>
</tr>
</table></div>	
</td>
</tr>
</table></div>
</td>
</tr>
<tr>	<td width='50%' vAlign='top'>
	<div align='left'><table cellpadding=2 cellspacing=2 border=0>		
	<tr><td colSpan=10 vAlign='top'><div align='left'><table width='100%' cellpadding=0 cellspacing=0 border=0><tr><td><div align='left'><table width='100%' cellpadding=0 cellspacing=0 border=0 height=27 style='background:#336699; border:2px solid; border-right:0px solid; border-color:#000000;'><tr><td><center><img src='images/blank.gif' width=24 height=1></center><center><img src='images/blue.jpg' style='border:1px solid; border-color:#FFFFFF;'></center><center><img src='images/blank.gif' width=24 height=1></center></td><td  width='100%' class='fontClass12' align='center' style='color:#FFFFFF;'>RECEIVING</td></tr></table></div></td><td vAlign='top' width=1 style='background:#336699; border-bottom:2px solid; border-bottom-color:#000000;'><div align='left'><img src='images/topCurl2.jpg'></div></td></tr></table></div><center><img src='images/shadow.png' height=29 width=760></center></td></tr><tr><td colSpan=10 style="border:0px dotted; border-color:#424242;" vAlign='top'><div align='left'><table cellpadding=0 cellspacing=0 border=0><tr>
<td onMouseOver="style.cursor='hand';" style="border-left:1px dashed; border-left-color:#FFFFFF; border-bottom:0px solid; border-top:0px solid; border-right:1px dashed; border-right-color:#FFFFFF;" onMouseOver="style.cursor='hand'" onClick="menuChoiceSet(63, 'receive_truck.php')"><center><table height='76' cellpadding=0 cellspacing=0 border=0 width=150><tr><td></td><td vAlign='bottom'><center><table width='91' height='58' cellpadding=0 cellspacing=0 border=0><tr><td width=1><div align='left'><img src='images/blank.gif' height='1' width='7'></div></td><td width='100%'><center><table width='100%' height='100%' cellpadding=0 cellspacing=0 border=0><tr><td vAlign='bottom' class='slideBlendTop' style='border:1px solid; border-color:#000000; border-bottom:0px solid;' onMouseOver="this.className='slideBlendTopOut'" onMouseOut="this.className='slideBlendTop'"><center><img src='images/truckload.png'></center></td></tr></table></center></td><td width=1 style='border-left:1px solid; border-left-color:#000000;'><div align='left'><img src='images/sideTop.jpg' height='54'></div></td></tr></table></center></td></tr><tr><td width=6><div align='center'><img src='images/led_red.png' width=6 height=23></div></td><td class='fontClass8' align='center' style='background:#FADEDB; color:#336699; border:1px solid; border-left:0px solid; border-color:#424242; padding:0px 2px;' height=10>Receive&nbsp;Truck</td>
</tr><tr><td></td><td vAlign='top'><center><table width='66' height='7' cellpadding=0 cellspacing=0 border=0><tr><td class='slideBlendTop' style='border:1px solid; border-color:#000000; border-top:0px solid;'><center><img src='images/blank.gif' width=1 height=7></center></td>
</tr><tr><td vAlign='top'><center><img src='images/bottomR.jpg'></center></td></tr></table></center></td></tr></table></center></td>
<td onMouseOver="style.cursor='hand';" style="border-left:1px dashed; border-left-color:#FFFFFF; border-bottom:0px solid; border-top:0px solid; border-right:1px dashed; border-right-color:#FFFFFF;" onMouseOver="style.cursor='hand'" onClick="menuChoiceSet(214, 'showLoadsByDay.php')"><center><table height='76' cellpadding=0 cellspacing=0 border=0 width=150><tr><td></td><td vAlign='bottom'><center><table width='91' height='58' cellpadding=0 cellspacing=0 border=0><tr><td width=1><div align='left'><img src='images/blank.gif' height='1' width='7'></div></td><td width='100%'><center><table width='100%' height='100%' cellpadding=0 cellspacing=0 border=0><tr><td vAlign='bottom' class='slideBlendTop' style='border:1px solid; border-color:#000000; border-bottom:0px solid;' onMouseOver="this.className='slideBlendTopOut'" onMouseOut="this.className='slideBlendTop'"><center><img src='images/loadids.png'></center></td></tr></table></center></td><td width=1 style='border-left:1px solid; border-left-color:#000000;'><div align='left'><img src='images/sideTop.jpg' height='54'></div></td></tr></table></center></td></tr><tr><td width=6><div align='center'><img src='images/led_red.png' width=6 height=23></div></td><td class='fontClass8' align='center' style='background:#FADEDB; color:#336699; border:1px solid; border-left:0px solid; border-color:#424242; padding:0px 2px;' height=10>Active&nbsp;Load&nbsp;IDs</td>
</tr><tr><td></td><td vAlign='top'><center><table width='66' height='7' cellpadding=0 cellspacing=0 border=0><tr><td class='slideBlendTop' style='border:1px solid; border-color:#000000; border-top:0px solid;'><center><img src='images/blank.gif' width=1 height=7></center></td>
</tr><tr><td vAlign='top'><center><img src='images/bottomR.jpg'></center></td></tr></table></center></td></tr></table></center></td>
<td onMouseOver="style.cursor='hand';" style="border-left:1px dashed; border-left-color:#FFFFFF; border-bottom:0px solid; border-top:0px solid; border-right:1px dashed; border-right-color:#FFFFFF;" onMouseOver="style.cursor='hand'" onClick="menuChoiceSet(224, 'receiptTools.php')"><center><table height='76' cellpadding=0 cellspacing=0 border=0 width=150><tr><td></td><td vAlign='bottom'><center><table width='91' height='58' cellpadding=0 cellspacing=0 border=0><tr><td width=1><div align='left'><img src='images/blank.gif' height='1' width='7'></div></td><td width='100%'><center><table width='100%' height='100%' cellpadding=0 cellspacing=0 border=0><tr><td vAlign='bottom' class='slideBlendTop' style='border:1px solid; border-color:#000000; border-bottom:0px solid;' onMouseOver="this.className='slideBlendTopOut'" onMouseOut="this.className='slideBlendTop'"><center><img src='images/receipttools.png'></center></td></tr></table></center></td><td width=1 style='border-left:1px solid; border-left-color:#000000;'><div align='left'><img src='images/sideTop.jpg' height='54'></div></td></tr></table></center></td></tr><tr><td width=6><div align='center'><img src='images/led_red.png' width=6 height=23></div></td><td class='fontClass8' align='center' style='background:#FADEDB; color:#336699; border:1px solid; border-left:0px solid; border-color:#424242; padding:0px 2px;' height=10>Receipt&nbsp;Tools</td>
</tr><tr><td></td><td vAlign='top'><center><table width='66' height='7' cellpadding=0 cellspacing=0 border=0><tr><td class='slideBlendTop' style='border:1px solid; border-color:#000000; border-top:0px solid;'><center><img src='images/blank.gif' width=1 height=7></center></td>
</tr><tr><td vAlign='top'><center><img src='images/bottomR.jpg'></center></td></tr></table></center></td></tr></table></center></td>
<td onMouseOver="style.cursor='hand';" style="border-left:1px dashed; border-left-color:#FFFFFF; border-bottom:0px solid; border-top:0px solid; border-right:1px dashed; border-right-color:#FFFFFF;" onMouseOver="style.cursor='hand'" onClick="menuChoiceSet(316, 'barcodeRePrintTruck.php')"><center><table height='76' cellpadding=0 cellspacing=0 border=0 width=150><tr><td></td><td vAlign='bottom'><center><table width='91' height='58' cellpadding=0 cellspacing=0 border=0><tr><td width=1><div align='left'><img src='images/blank.gif' height='1' width='7'></div></td><td width='100%'><center><table width='100%' height='100%' cellpadding=0 cellspacing=0 border=0><tr><td vAlign='bottom' class='slideBlendTop' style='border:1px solid; border-color:#000000; border-bottom:0px solid;' onMouseOver="this.className='slideBlendTopOut'" onMouseOut="this.className='slideBlendTop'"><center><img src='images/barcode8.png'></center></td></tr></table></center></td><td width=1 style='border-left:1px solid; border-left-color:#000000;'><div align='left'><img src='images/sideTop.jpg' height='54'></div></td></tr></table></center></td></tr><tr><td width=6><div align='center'><img src='images/led_red.png' width=6 height=23></div></td><td class='fontClass8' align='center' style='background:#FADEDB; color:#336699; border:1px solid; border-left:0px solid; border-color:#424242; padding:0px 2px;' height=10>Load&nbsp;ID&nbsp;Label&nbsp;Reprint</td>
</tr><tr><td></td><td vAlign='top'><center><table width='66' height='7' cellpadding=0 cellspacing=0 border=0><tr><td class='slideBlendTop' style='border:1px solid; border-color:#000000; border-top:0px solid;'><center><img src='images/blank.gif' width=1 height=7></center></td>
</tr><tr><td vAlign='top'><center><img src='images/bottomR.jpg'></center></td></tr></table></center></td></tr></table></center></td>
<td onMouseOver="style.cursor='hand';" style="border-left:1px dashed; border-left-color:#FFFFFF; border-bottom:0px solid; border-top:0px solid; border-right:1px dashed; border-right-color:#FFFFFF;" onMouseOver="style.cursor='hand'" onClick="menuChoiceSet(317, 'printReportTruck.php')"><center><table height='76' cellpadding=0 cellspacing=0 border=0 width=150><tr><td></td><td vAlign='bottom'><center><table width='91' height='58' cellpadding=0 cellspacing=0 border=0><tr><td width=1><div align='left'><img src='images/blank.gif' height='1' width='7'></div></td><td width='100%'><center><table width='100%' height='100%' cellpadding=0 cellspacing=0 border=0><tr><td vAlign='bottom' class='slideBlendTop' style='border:1px solid; border-color:#000000; border-bottom:0px solid;' onMouseOver="this.className='slideBlendTopOut'" onMouseOut="this.className='slideBlendTop'"><center><img src='images/listreceive.png'></center></td></tr></table></center></td><td width=1 style='border-left:1px solid; border-left-color:#000000;'><div align='left'><img src='images/sideTop.jpg' height='54'></div></td></tr></table></center></td></tr><tr><td width=6><div align='center'><img src='images/led_red.png' width=6 height=23></div></td><td class='fontClass8' align='center' style='background:#FADEDB; color:#336699; border:1px solid; border-left:0px solid; border-color:#424242; padding:0px 2px;' height=10>Load&nbsp;Reports</td>
</tr><tr><td></td><td vAlign='top'><center><table width='66' height='7' cellpadding=0 cellspacing=0 border=0><tr><td class='slideBlendTop' style='border:1px solid; border-color:#000000; border-top:0px solid;'><center><img src='images/blank.gif' width=1 height=7></center></td>
</tr><tr><td vAlign='top'><center><img src='images/bottomR.jpg'></center></td></tr></table></center></td></tr></table></center></td></tr></table></center></td></tr><tr><td colSpan=10 vAlign='top'><div align='left'><table width='100%' cellpadding=0 cellspacing=0 border=0><tr><td><div align='left'><table width='100%' cellpadding=0 cellspacing=0 border=0 height=27 style='background:#336699; border:2px solid; border-right:0px solid; border-color:#000000;'><tr><td><center><img src='images/blank.gif' width=24 height=1></center><center><img src='images/blue.jpg' style='border:1px solid; border-color:#FFFFFF;'></center><center><img src='images/blank.gif' width=24 height=1></center></td><td  width='100%' class='fontClass12' align='center' style='color:#FFFFFF;'>INSPECTION</td></tr></table></div></td><td vAlign='top' width=1 style='background:#336699; border-bottom:2px solid; border-bottom-color:#000000;'><div align='left'><img src='images/topCurl2.jpg'></div></td></tr></table></div><center><img src='images/shadow.png' height=29 width=760></center></td></tr><tr><td colSpan=10 style="border:0px dotted; border-color:#424242;" vAlign='top'><div align='left'><table cellpadding=0 cellspacing=0 border=0><tr>
<td onMouseOver="style.cursor='hand';" style="border-left:1px dashed; border-left-color:#FFFFFF; border-bottom:0px solid; border-top:0px solid; border-right:1px dashed; border-right-color:#FFFFFF;" onMouseOver="style.cursor='hand'" onClick="menuChoiceSet(67, 'inspectionHome.php')"><center><table height='76' cellpadding=0 cellspacing=0 border=0 width=150><tr><td></td><td vAlign='bottom'><center><table width='91' height='58' cellpadding=0 cellspacing=0 border=0><tr><td width=1><div align='left'><img src='images/blank.gif' height='1' width='7'></div></td><td width='100%'><center><table width='100%' height='100%' cellpadding=0 cellspacing=0 border=0><tr><td vAlign='bottom' class='slideBlendTop' style='border:1px solid; border-color:#000000; border-bottom:0px solid;' onMouseOver="this.className='slideBlendTopOut'" onMouseOut="this.className='slideBlendTop'"><center><img src='images/inspectionTools.png'></center></td></tr></table></center></td><td width=1 style='border-left:1px solid; border-left-color:#000000;'><div align='left'><img src='images/sideTop.jpg' height='54'></div></td></tr></table></center></td></tr><tr><td width=6><div align='center'><img src='images/led_red.png' width=6 height=23></div></td><td class='fontClass8' align='center' style='background:#FADEDB; color:#336699; border:1px solid; border-left:0px solid; border-color:#424242; padding:0px 2px;' height=10>Inspection&nbsp;Home</td>
</tr><tr><td></td><td vAlign='top'><center><table width='66' height='7' cellpadding=0 cellspacing=0 border=0><tr><td class='slideBlendTop' style='border:1px solid; border-color:#000000; border-top:0px solid;'><center><img src='images/blank.gif' width=1 height=7></center></td>
</tr><tr><td vAlign='top'><center><img src='images/bottomR.jpg'></center></td></tr></table></center></td></tr></table></center></td>
<td onMouseOver="style.cursor='hand';" style="border-left:1px dashed; border-left-color:#FFFFFF; border-bottom:0px solid; border-top:0px solid; border-right:1px dashed; border-right-color:#FFFFFF;" onMouseOver="style.cursor='hand'" onClick="doPopup(105, 'intensiveSearch.php')"><center><table height='76' cellpadding=0 cellspacing=0 border=0 width=150><tr><td></td><td vAlign='bottom'><center><table width='91' height='58' cellpadding=0 cellspacing=0 border=0><tr><td width=1><div align='left'><img src='images/blank.gif' height='1' width='7'></div></td><td width='100%'><center><table width='100%' height='100%' cellpadding=0 cellspacing=0 border=0><tr><td vAlign='bottom' class='slideBlendTop' style='border:1px solid; border-color:#000000; border-bottom:0px solid;' onMouseOver="this.className='slideBlendTopOut'" onMouseOut="this.className='slideBlendTop'"><center><img src='images/realsearch.png'></center></td></tr></table></center></td><td width=1 style='border-left:1px solid; border-left-color:#000000;'><div align='left'><img src='images/sideTop.jpg' height='54'></div></td></tr></table></center></td></tr><tr><td width=6><div align='center'><img src='images/led_red.png' width=6 height=23></div></td><td class='fontClass8' align='center' style='background:#FADEDB; color:#336699; border:1px solid; border-left:0px solid; border-color:#424242; padding:0px 2px;' height=10>Search&nbsp;Detail</td>
</tr><tr><td></td><td vAlign='top'><center><table width='66' height='7' cellpadding=0 cellspacing=0 border=0><tr><td class='slideBlendTop' style='border:1px solid; border-color:#000000; border-top:0px solid;'><center><img src='images/blank.gif' width=1 height=7></center></td>
</tr><tr><td vAlign='top'><center><img src='images/bottomR.jpg'></center></td></tr></table></center></td></tr></table></center></td>
<td onMouseOver="style.cursor='hand';" style="border-left:1px dashed; border-left-color:#FFFFFF; border-bottom:0px solid; border-top:0px solid; border-right:1px dashed; border-right-color:#FFFFFF;" onMouseOver="style.cursor='hand'" onClick="menuChoiceSet(156, 'inspectorNotes.php')"><center><table height='76' cellpadding=0 cellspacing=0 border=0 width=150><tr><td></td><td vAlign='bottom'><center><table width='91' height='58' cellpadding=0 cellspacing=0 border=0><tr><td width=1><div align='left'><img src='images/blank.gif' height='1' width='7'></div></td><td width='100%'><center><table width='100%' height='100%' cellpadding=0 cellspacing=0 border=0><tr><td vAlign='bottom' class='slideBlendTop' style='border:1px solid; border-color:#000000; border-bottom:0px solid;' onMouseOver="this.className='slideBlendTopOut'" onMouseOut="this.className='slideBlendTop'"><center><img src='images/inspectornotes.png'></center></td></tr></table></center></td><td width=1 style='border-left:1px solid; border-left-color:#000000;'><div align='left'><img src='images/sideTop.jpg' height='54'></div></td></tr></table></center></td></tr><tr><td width=6><div align='center'><img src='images/led_green.png' width=6 height=23></div></td><td class='fontClass8' align='center' style='background:#E3FAE3; color:#336699; border:1px solid; border-left:0px solid; border-color:#424242; padding:0px 2px;' height=10>Inspector&nbsp;Notes</td>
</tr><tr><td></td><td vAlign='top'><center><table width='66' height='7' cellpadding=0 cellspacing=0 border=0><tr><td class='slideBlendTop' style='border:1px solid; border-color:#000000; border-top:0px solid;'><center><img src='images/blank.gif' width=1 height=7></center></td>
</tr><tr><td vAlign='top'><center><img src='images/bottomR.jpg'></center></td></tr></table></center></td></tr></table></center></td>
<td onMouseOver="style.cursor='hand';" style="border-left:1px dashed; border-left-color:#FFFFFF; border-bottom:0px solid; border-top:0px solid; border-right:1px dashed; border-right-color:#FFFFFF;" onMouseOver="style.cursor='hand'" onClick="menuChoiceSet(174, 'inspectViewPage.php')"><center><table height='76' cellpadding=0 cellspacing=0 border=0 width=150><tr><td></td><td vAlign='bottom'><center><table width='91' height='58' cellpadding=0 cellspacing=0 border=0><tr><td width=1><div align='left'><img src='images/blank.gif' height='1' width='7'></div></td><td width='100%'><center><table width='100%' height='100%' cellpadding=0 cellspacing=0 border=0><tr><td vAlign='bottom' class='slideBlendTop' style='border:1px solid; border-color:#000000; border-bottom:0px solid;' onMouseOver="this.className='slideBlendTopOut'" onMouseOut="this.className='slideBlendTop'"><center><img src='images/inspectListView.png'></center></td></tr></table></center></td><td width=1 style='border-left:1px solid; border-left-color:#000000;'><div align='left'><img src='images/sideTop.jpg' height='54'></div></td></tr></table></center></td></tr><tr><td width=6><div align='center'><img src='images/led_green.png' width=6 height=23></div></td><td class='fontClass8' align='center' style='background:#E3FAE3; color:#336699; border:1px solid; border-left:0px solid; border-color:#424242; padding:0px 2px;' height=10>Inspection&nbsp;List&nbsp;View</td>
</tr><tr><td></td><td vAlign='top'><center><table width='66' height='7' cellpadding=0 cellspacing=0 border=0><tr><td class='slideBlendTop' style='border:1px solid; border-color:#000000; border-top:0px solid;'><center><img src='images/blank.gif' width=1 height=7></center></td>
</tr><tr><td vAlign='top'><center><img src='images/bottomR.jpg'></center></td></tr></table></center></td></tr></table></center></td>
<td onMouseOver="style.cursor='hand';" style="border-left:1px dashed; border-left-color:#FFFFFF; border-bottom:0px solid; border-top:0px solid; border-right:1px dashed; border-right-color:#FFFFFF;" onMouseOver="style.cursor='hand'" onClick="menuChoiceSet(177, 'findThisNC.php')"><center><table height='76' cellpadding=0 cellspacing=0 border=0 width=150><tr><td></td><td vAlign='bottom'><center><table width='91' height='58' cellpadding=0 cellspacing=0 border=0><tr><td width=1><div align='left'><img src='images/blank.gif' height='1' width='7'></div></td><td width='100%'><center><table width='100%' height='100%' cellpadding=0 cellspacing=0 border=0><tr><td vAlign='bottom' class='slideBlendTop' style='border:1px solid; border-color:#000000; border-bottom:0px solid;' onMouseOver="this.className='slideBlendTopOut'" onMouseOut="this.className='slideBlendTop'"><center><img src='images/viewmag1.png'></center></td></tr></table></center></td><td width=1 style='border-left:1px solid; border-left-color:#000000;'><div align='left'><img src='images/sideTop.jpg' height='54'></div></td></tr></table></center></td></tr><tr><td width=6><div align='center'><img src='images/led_red.png' width=6 height=23></div></td><td class='fontClass8' align='center' style='background:#FADEDB; color:#336699; border:1px solid; border-left:0px solid; border-color:#424242; padding:0px 2px;' height=10>Find&nbsp;Non&nbsp;Conforming</td>
</tr><tr><td></td><td vAlign='top'><center><table width='66' height='7' cellpadding=0 cellspacing=0 border=0><tr><td class='slideBlendTop' style='border:1px solid; border-color:#000000; border-top:0px solid;'><center><img src='images/blank.gif' width=1 height=7></center></td>
</tr><tr><td vAlign='top'><center><img src='images/bottomR.jpg'></center></td></tr></table></center></td></tr></table></center></td></tr><tr>
<td onMouseOver="style.cursor='hand';" style="border-left:1px dashed; border-left-color:#FFFFFF; border-bottom:0px solid; border-top:0px solid; border-right:1px dashed; border-right-color:#FFFFFF;" onMouseOver="style.cursor='hand'" onClick="menuChoiceSet(182, 'inspectionHomeQuick.php')"><center><table height='76' cellpadding=0 cellspacing=0 border=0 width=150><tr><td></td><td vAlign='bottom'><center><table width='91' height='58' cellpadding=0 cellspacing=0 border=0><tr><td width=1><div align='left'><img src='images/blank.gif' height='1' width='7'></div></td><td width='100%'><center><table width='100%' height='100%' cellpadding=0 cellspacing=0 border=0><tr><td vAlign='bottom' class='slideBlendTop' style='border:1px solid; border-color:#000000; border-bottom:0px solid;' onMouseOver="this.className='slideBlendTopOut'" onMouseOut="this.className='slideBlendTop'"><center><img src='images/inspectionToolsModifed.png'></center></td></tr></table></center></td><td width=1 style='border-left:1px solid; border-left-color:#000000;'><div align='left'><img src='images/sideTop.jpg' height='54'></div></td></tr></table></center></td></tr><tr><td width=6><div align='center'><img src='images/led_red.png' width=6 height=23></div></td><td class='fontClass8' align='center' style='background:#FADEDB; color:#336699; border:1px solid; border-left:0px solid; border-color:#424242; padding:0px 2px;' height=10>Inspection&nbsp;Modified</td>
</tr><tr><td></td><td vAlign='top'><center><table width='66' height='7' cellpadding=0 cellspacing=0 border=0><tr><td class='slideBlendTop' style='border:1px solid; border-color:#000000; border-top:0px solid;'><center><img src='images/blank.gif' width=1 height=7></center></td>
</tr><tr><td vAlign='top'><center><img src='images/bottomR.jpg'></center></td></tr></table></center></td></tr></table></center></td>
<td onMouseOver="style.cursor='hand';" style="border-left:1px dashed; border-left-color:#FFFFFF; border-bottom:0px solid; border-top:0px solid; border-right:1px dashed; border-right-color:#FFFFFF;" onMouseOver="style.cursor='hand'" onClick="menuChoiceSet(267, 'inspectionHomeFP.php')"><center><table height='76' cellpadding=0 cellspacing=0 border=0 width=150><tr><td></td><td vAlign='bottom'><center><table width='91' height='58' cellpadding=0 cellspacing=0 border=0><tr><td width=1><div align='left'><img src='images/blank.gif' height='1' width='7'></div></td><td width='100%'><center><table width='100%' height='100%' cellpadding=0 cellspacing=0 border=0><tr><td vAlign='bottom' class='slideBlendTop' style='border:1px solid; border-color:#000000; border-bottom:0px solid;' onMouseOver="this.className='slideBlendTopOut'" onMouseOut="this.className='slideBlendTop'"><center><img src='images/fm.png'></center></td></tr></table></center></td><td width=1 style='border-left:1px solid; border-left-color:#000000;'><div align='left'><img src='images/sideTop.jpg' height='54'></div></td></tr></table></center></td></tr><tr><td width=6><div align='center'><img src='images/led_red.png' width=6 height=23></div></td><td class='fontClass8' align='center' style='background:#FADEDB; color:#336699; border:1px solid; border-left:0px solid; border-color:#424242; padding:0px 2px;' height=10>FleetPride&nbsp;Inspection</td>
</tr><tr><td></td><td vAlign='top'><center><table width='66' height='7' cellpadding=0 cellspacing=0 border=0><tr><td class='slideBlendTop' style='border:1px solid; border-color:#000000; border-top:0px solid;'><center><img src='images/blank.gif' width=1 height=7></center></td>
</tr><tr><td vAlign='top'><center><img src='images/bottomR.jpg'></center></td></tr></table></center></td></tr></table></center></td></table></center></td></tr><tr><td colSpan=10 vAlign='top'><div align='left'><table width='100%' cellpadding=0 cellspacing=0 border=0><tr><td><div align='left'><table width='100%' cellpadding=0 cellspacing=0 border=0 height=27 style='background:#336699; border:2px solid; border-right:0px solid; border-color:#000000;'><tr><td><center><img src='images/blank.gif' width=24 height=1></center><center><img src='images/blue.jpg' style='border:1px solid; border-color:#FFFFFF;'></center><center><img src='images/blank.gif' width=24 height=1></center></td><td  width='100%' class='fontClass12' align='center' style='color:#FFFFFF;'>PROCESSING</td></tr></table></div></td><td vAlign='top' width=1 style='background:#336699; border-bottom:2px solid; border-bottom-color:#000000;'><div align='left'><img src='images/topCurl2.jpg'></div></td></tr></table></div><center><img src='images/shadow.png' height=29 width=760></center></td></tr><tr><td colSpan=10 style="border:0px dotted; border-color:#424242;" vAlign='top'><div align='left'><table cellpadding=0 cellspacing=0 border=0><tr>
<td onMouseOver="style.cursor='hand';" style="border-left:1px dashed; border-left-color:#FFFFFF; border-bottom:0px solid; border-top:0px solid; border-right:1px dashed; border-right-color:#FFFFFF;" onMouseOver="style.cursor='hand'" onClick="menuChoiceSet(124, 'transition/coreviewlist.php')"><center><table height='76' cellpadding=0 cellspacing=0 border=0 width=150><tr><td></td><td vAlign='bottom'><center><table width='91' height='58' cellpadding=0 cellspacing=0 border=0><tr><td width=1><div align='left'><img src='images/blank.gif' height='1' width='7'></div></td><td width='100%'><center><table width='100%' height='100%' cellpadding=0 cellspacing=0 border=0><tr><td vAlign='bottom' class='slideBlendTop' style='border:1px solid; border-color:#000000; border-bottom:0px solid;' onMouseOver="this.className='slideBlendTopOut'" onMouseOut="this.className='slideBlendTop'"><center><img src='images/processA.png'></center></td></tr></table></center></td><td width=1 style='border-left:1px solid; border-left-color:#000000;'><div align='left'><img src='images/sideTop.jpg' height='54'></div></td></tr></table></center></td></tr><tr><td width=6><div align='center'><img src='images/led_red.png' width=6 height=23></div></td><td class='fontClass8' align='center' style='background:#FADEDB; color:#336699; border:1px solid; border-left:0px solid; border-color:#424242; padding:0px 2px;' height=10>CNH&nbsp;Processing</td>
</tr><tr><td></td><td vAlign='top'><center><table width='66' height='7' cellpadding=0 cellspacing=0 border=0><tr><td class='slideBlendTop' style='border:1px solid; border-color:#000000; border-top:0px solid;'><center><img src='images/blank.gif' width=1 height=7></center></td>
</tr><tr><td vAlign='top'><center><img src='images/bottomR.jpg'></center></td></tr></table></center></td></tr></table></center></td>
<td onMouseOver="style.cursor='hand';" style="border-left:1px dashed; border-left-color:#FFFFFF; border-bottom:0px solid; border-top:0px solid; border-right:1px dashed; border-right-color:#FFFFFF;" onMouseOver="style.cursor='hand'" onClick="menuChoiceSet(175, 'transition/coreviewlistView.php')"><center><table height='76' cellpadding=0 cellspacing=0 border=0 width=150><tr><td></td><td vAlign='bottom'><center><table width='91' height='58' cellpadding=0 cellspacing=0 border=0><tr><td width=1><div align='left'><img src='images/blank.gif' height='1' width='7'></div></td><td width='100%'><center><table width='100%' height='100%' cellpadding=0 cellspacing=0 border=0><tr><td vAlign='bottom' class='slideBlendTop' style='border:1px solid; border-color:#000000; border-bottom:0px solid;' onMouseOver="this.className='slideBlendTopOut'" onMouseOut="this.className='slideBlendTop'"><center><img src='images/doProcess48R.png'></center></td></tr></table></center></td><td width=1 style='border-left:1px solid; border-left-color:#000000;'><div align='left'><img src='images/sideTop.jpg' height='54'></div></td></tr></table></center></td></tr><tr><td width=6><div align='center'><img src='images/led_red.png' width=6 height=23></div></td><td class='fontClass8' align='center' style='background:#FADEDB; color:#336699; border:1px solid; border-left:0px solid; border-color:#424242; padding:0px 2px;' height=10>CNH&nbsp;Processing&nbsp;View</td>
</tr><tr><td></td><td vAlign='top'><center><table width='66' height='7' cellpadding=0 cellspacing=0 border=0><tr><td class='slideBlendTop' style='border:1px solid; border-color:#000000; border-top:0px solid;'><center><img src='images/blank.gif' width=1 height=7></center></td>
</tr><tr><td vAlign='top'><center><img src='images/bottomR.jpg'></center></td></tr></table></center></td></tr></table></center></td>
<td onMouseOver="style.cursor='hand';" style="border-left:1px dashed; border-left-color:#FFFFFF; border-bottom:0px solid; border-top:0px solid; border-right:1px dashed; border-right-color:#FFFFFF;" onMouseOver="style.cursor='hand'" onClick="menuChoiceSet(225, 'checkPAA.php')"><center><table height='76' cellpadding=0 cellspacing=0 border=0 width=150><tr><td></td><td vAlign='bottom'><center><table width='91' height='58' cellpadding=0 cellspacing=0 border=0><tr><td width=1><div align='left'><img src='images/blank.gif' height='1' width='7'></div></td><td width='100%'><center><table width='100%' height='100%' cellpadding=0 cellspacing=0 border=0><tr><td vAlign='bottom' class='slideBlendTop' style='border:1px solid; border-color:#000000; border-bottom:0px solid;' onMouseOver="this.className='slideBlendTopOut'" onMouseOut="this.className='slideBlendTop'"><center><img src='images/reCheckPay.png'></center></td></tr></table></center></td><td width=1 style='border-left:1px solid; border-left-color:#000000;'><div align='left'><img src='images/sideTop.jpg' height='54'></div></td></tr></table></center></td></tr><tr><td width=6><div align='center'><img src='images/led_red.png' width=6 height=23></div></td><td class='fontClass8' align='center' style='background:#FADEDB; color:#336699; border:1px solid; border-left:0px solid; border-color:#424242; padding:0px 2px;' height=10>PAA&nbsp;Administration</td>
</tr><tr><td></td><td vAlign='top'><center><table width='66' height='7' cellpadding=0 cellspacing=0 border=0><tr><td class='slideBlendTop' style='border:1px solid; border-color:#000000; border-top:0px solid;'><center><img src='images/blank.gif' width=1 height=7></center></td>
</tr><tr><td vAlign='top'><center><img src='images/bottomR.jpg'></center></td></tr></table></center></td></tr></table></center></td>
<td onMouseOver="style.cursor='hand';" style="border-left:1px dashed; border-left-color:#FFFFFF; border-bottom:0px solid; border-top:0px solid; border-right:1px dashed; border-right-color:#FFFFFF;" onMouseOver="style.cursor='hand'" onClick="menuChoiceSet(275, 'checkEPAPAA.php')"><center><table height='76' cellpadding=0 cellspacing=0 border=0 width=150><tr><td></td><td vAlign='bottom'><center><table width='91' height='58' cellpadding=0 cellspacing=0 border=0><tr><td width=1><div align='left'><img src='images/blank.gif' height='1' width='7'></div></td><td width='100%'><center><table width='100%' height='100%' cellpadding=0 cellspacing=0 border=0><tr><td vAlign='bottom' class='slideBlendTop' style='border:1px solid; border-color:#000000; border-bottom:0px solid;' onMouseOver="this.className='slideBlendTopOut'" onMouseOut="this.className='slideBlendTop'"><center><img src='images/reCheckPay.png'></center></td></tr></table></center></td><td width=1 style='border-left:1px solid; border-left-color:#000000;'><div align='left'><img src='images/sideTop.jpg' height='54'></div></td></tr></table></center></td></tr><tr><td width=6><div align='center'><img src='images/led_red.png' width=6 height=23></div></td><td class='fontClass8' align='center' style='background:#FADEDB; color:#336699; border:1px solid; border-left:0px solid; border-color:#424242; padding:0px 2px;' height=10>EPA&nbsp;PAA&nbsp;Admin</td>
</tr><tr><td></td><td vAlign='top'><center><table width='66' height='7' cellpadding=0 cellspacing=0 border=0><tr><td class='slideBlendTop' style='border:1px solid; border-color:#000000; border-top:0px solid;'><center><img src='images/blank.gif' width=1 height=7></center></td>
</tr><tr><td vAlign='top'><center><img src='images/bottomR.jpg'></center></td></tr></table></center></td></tr></table></center></td>
<td onMouseOver="style.cursor='hand';" style="border-left:1px dashed; border-left-color:#FFFFFF; border-bottom:0px solid; border-top:0px solid; border-right:1px dashed; border-right-color:#FFFFFF;" onMouseOver="style.cursor='hand'" onClick="menuChoiceSet(229, 'cnhProcessingIssues.php')"><center><table height='76' cellpadding=0 cellspacing=0 border=0 width=150><tr><td></td><td vAlign='bottom'><center><table width='91' height='58' cellpadding=0 cellspacing=0 border=0><tr><td width=1><div align='left'><img src='images/blank.gif' height='1' width='7'></div></td><td width='100%'><center><table width='100%' height='100%' cellpadding=0 cellspacing=0 border=0><tr><td vAlign='bottom' class='slideBlendTop' style='border:1px solid; border-color:#000000; border-bottom:0px solid;' onMouseOver="this.className='slideBlendTopOut'" onMouseOut="this.className='slideBlendTop'"><center><img src='images/pissues.png'></center></td></tr></table></center></td><td width=1 style='border-left:1px solid; border-left-color:#000000;'><div align='left'><img src='images/sideTop.jpg' height='54'></div></td></tr></table></center></td></tr><tr><td width=6><div align='center'><img src='images/led_red.png' width=6 height=23></div></td><td class='fontClass8' align='center' style='background:#FADEDB; color:#336699; border:1px solid; border-left:0px solid; border-color:#424242; padding:0px 2px;' height=10>CNH&nbsp;Processing&nbsp;Issues</td>
</tr><tr><td></td><td vAlign='top'><center><table width='66' height='7' cellpadding=0 cellspacing=0 border=0><tr><td class='slideBlendTop' style='border:1px solid; border-color:#000000; border-top:0px solid;'><center><img src='images/blank.gif' width=1 height=7></center></td>
</tr><tr><td vAlign='top'><center><img src='images/bottomR.jpg'></center></td></tr></table></center></td></tr></table></center></td></tr><tr>
<td onMouseOver="style.cursor='hand';" style="border-left:1px dashed; border-left-color:#FFFFFF; border-bottom:0px solid; border-top:0px solid; border-right:1px dashed; border-right-color:#FFFFFF;" onMouseOver="style.cursor='hand'" onClick="menuChoiceSet(255, 'transition/bobcatlist.php')"><center><table height='76' cellpadding=0 cellspacing=0 border=0 width=150><tr><td></td><td vAlign='bottom'><center><table width='91' height='58' cellpadding=0 cellspacing=0 border=0><tr><td width=1><div align='left'><img src='images/blank.gif' height='1' width='7'></div></td><td width='100%'><center><table width='100%' height='100%' cellpadding=0 cellspacing=0 border=0><tr><td vAlign='bottom' class='slideBlendTop' style='border:1px solid; border-color:#000000; border-bottom:0px solid;' onMouseOver="this.className='slideBlendTopOut'" onMouseOut="this.className='slideBlendTop'"><center><img src='images/processB.png'></center></td></tr></table></center></td><td width=1 style='border-left:1px solid; border-left-color:#000000;'><div align='left'><img src='images/sideTop.jpg' height='54'></div></td></tr></table></center></td></tr><tr><td width=6><div align='center'><img src='images/led_red.png' width=6 height=23></div></td><td class='fontClass8' align='center' style='background:#FADEDB; color:#336699; border:1px solid; border-left:0px solid; border-color:#424242; padding:0px 2px;' height=10>Bobcat&nbsp;Processing</td>
</tr><tr><td></td><td vAlign='top'><center><table width='66' height='7' cellpadding=0 cellspacing=0 border=0><tr><td class='slideBlendTop' style='border:1px solid; border-color:#000000; border-top:0px solid;'><center><img src='images/blank.gif' width=1 height=7></center></td>
</tr><tr><td vAlign='top'><center><img src='images/bottomR.jpg'></center></td></tr></table></center></td></tr></table></center></td>
<td onMouseOver="style.cursor='hand';" style="border-left:1px dashed; border-left-color:#FFFFFF; border-bottom:0px solid; border-top:0px solid; border-right:1px dashed; border-right-color:#FFFFFF;" onMouseOver="style.cursor='hand'" onClick="menuChoiceSet(282, 'transition/emd_list.php')"><center><table height='76' cellpadding=0 cellspacing=0 border=0 width=150><tr><td></td><td vAlign='bottom'><center><table width='91' height='58' cellpadding=0 cellspacing=0 border=0><tr><td width=1><div align='left'><img src='images/blank.gif' height='1' width='7'></div></td><td width='100%'><center><table width='100%' height='100%' cellpadding=0 cellspacing=0 border=0><tr><td vAlign='bottom' class='slideBlendTop' style='border:1px solid; border-color:#000000; border-bottom:0px solid;' onMouseOver="this.className='slideBlendTopOut'" onMouseOut="this.className='slideBlendTop'"><center><img src='images/emd48.png'></center></td></tr></table></center></td><td width=1 style='border-left:1px solid; border-left-color:#000000;'><div align='left'><img src='images/sideTop.jpg' height='54'></div></td></tr></table></center></td></tr><tr><td width=6><div align='center'><img src='images/led_red.png' width=6 height=23></div></td><td class='fontClass8' align='center' style='background:#FADEDB; color:#336699; border:1px solid; border-left:0px solid; border-color:#424242; padding:0px 2px;' height=10>EMD&nbsp;Processing</td>
</tr><tr><td></td><td vAlign='top'><center><table width='66' height='7' cellpadding=0 cellspacing=0 border=0><tr><td class='slideBlendTop' style='border:1px solid; border-color:#000000; border-top:0px solid;'><center><img src='images/blank.gif' width=1 height=7></center></td>
</tr><tr><td vAlign='top'><center><img src='images/bottomR.jpg'></center></td></tr></table></center></td></tr></table></center></td>
<td onMouseOver="style.cursor='hand';" style="border-left:1px dashed; border-left-color:#FFFFFF; border-bottom:0px solid; border-top:0px solid; border-right:1px dashed; border-right-color:#FFFFFF;" onMouseOver="style.cursor='hand'" onClick="menuChoiceSet(284, 'emd_pers_interface.php')"><center><table height='76' cellpadding=0 cellspacing=0 border=0 width=150><tr><td></td><td vAlign='bottom'><center><table width='91' height='58' cellpadding=0 cellspacing=0 border=0><tr><td width=1><div align='left'><img src='images/blank.gif' height='1' width='7'></div></td><td width='100%'><center><table width='100%' height='100%' cellpadding=0 cellspacing=0 border=0><tr><td vAlign='bottom' class='slideBlendTop' style='border:1px solid; border-color:#000000; border-bottom:0px solid;' onMouseOver="this.className='slideBlendTopOut'" onMouseOut="this.className='slideBlendTop'"><center><img src='images/default48.png'></center></td></tr></table></center></td><td width=1 style='border-left:1px solid; border-left-color:#000000;'><div align='left'><img src='images/sideTop.jpg' height='54'></div></td></tr></table></center></td></tr><tr><td width=6><div align='center'><img src='images/led_red.png' width=6 height=23></div></td><td class='fontClass8' align='center' style='background:#FADEDB; color:#336699; border:1px solid; border-left:0px solid; border-color:#424242; padding:0px 2px;' height=10>EMD&nbsp;PERS&nbsp;Management</td>
</tr><tr><td></td><td vAlign='top'><center><table width='66' height='7' cellpadding=0 cellspacing=0 border=0><tr><td class='slideBlendTop' style='border:1px solid; border-color:#000000; border-top:0px solid;'><center><img src='images/blank.gif' width=1 height=7></center></td>
</tr><tr><td vAlign='top'><center><img src='images/bottomR.jpg'></center></td></tr></table></center></td></tr></table></center></td>
<td onMouseOver="style.cursor='hand';" style="border-left:1px dashed; border-left-color:#FFFFFF; border-bottom:0px solid; border-top:0px solid; border-right:1px dashed; border-right-color:#FFFFFF;" onMouseOver="style.cursor='hand'" onClick="menuChoiceSet(326, 'transition/yanmarlist.php')"><center><table height='76' cellpadding=0 cellspacing=0 border=0 width=150><tr><td></td><td vAlign='bottom'><center><table width='91' height='58' cellpadding=0 cellspacing=0 border=0><tr><td width=1><div align='left'><img src='images/blank.gif' height='1' width='7'></div></td><td width='100%'><center><table width='100%' height='100%' cellpadding=0 cellspacing=0 border=0><tr><td vAlign='bottom' class='slideBlendTop' style='border:1px solid; border-color:#000000; border-bottom:0px solid;' onMouseOver="this.className='slideBlendTopOut'" onMouseOut="this.className='slideBlendTop'"><center><img src='images/processB.png'></center></td></tr></table></center></td><td width=1 style='border-left:1px solid; border-left-color:#000000;'><div align='left'><img src='images/sideTop.jpg' height='54'></div></td></tr></table></center></td></tr><tr><td width=6><div align='center'><img src='images/led_red.png' width=6 height=23></div></td><td class='fontClass8' align='center' style='background:#FADEDB; color:#336699; border:1px solid; border-left:0px solid; border-color:#424242; padding:0px 2px;' height=10>Yanmar&nbsp;Processing</td>
</tr><tr><td></td><td vAlign='top'><center><table width='66' height='7' cellpadding=0 cellspacing=0 border=0><tr><td class='slideBlendTop' style='border:1px solid; border-color:#000000; border-top:0px solid;'><center><img src='images/blank.gif' width=1 height=7></center></td>
</tr><tr><td vAlign='top'><center><img src='images/bottomR.jpg'></center></td></tr></table></center></td></tr></table></center></td></table></center></td></tr><tr><td colSpan=10 vAlign='top'><div align='left'><table width='100%' cellpadding=0 cellspacing=0 border=0><tr><td><div align='left'><table width='100%' cellpadding=0 cellspacing=0 border=0 height=27 style='background:#336699; border:2px solid; border-right:0px solid; border-color:#000000;'><tr><td><center><img src='images/blank.gif' width=24 height=1></center><center><img src='images/blue.jpg' style='border:1px solid; border-color:#FFFFFF;'></center><center><img src='images/blank.gif' width=24 height=1></center></td><td  width='100%' class='fontClass12' align='center' style='color:#FFFFFF;'>DATA&nbsp;ADMIN</td></tr></table></div></td><td vAlign='top' width=1 style='background:#336699; border-bottom:2px solid; border-bottom-color:#000000;'><div align='left'><img src='images/topCurl2.jpg'></div></td></tr></table></div><center><img src='images/shadow.png' height=29 width=760></center></td></tr><tr><td colSpan=10 style="border:0px dotted; border-color:#424242;" vAlign='top'><div align='left'><table cellpadding=0 cellspacing=0 border=0><tr>
<td onMouseOver="style.cursor='hand';" style="border-left:1px dashed; border-left-color:#FFFFFF; border-bottom:0px solid; border-top:0px solid; border-right:1px dashed; border-right-color:#FFFFFF;" onMouseOver="style.cursor='hand'" onClick="menuChoiceSet(325, 'manageEPAIssues.php')"><center><table height='76' cellpadding=0 cellspacing=0 border=0 width=150><tr><td></td><td vAlign='bottom'><center><table width='91' height='58' cellpadding=0 cellspacing=0 border=0><tr><td width=1><div align='left'><img src='images/blank.gif' height='1' width='7'></div></td><td width='100%'><center><table width='100%' height='100%' cellpadding=0 cellspacing=0 border=0><tr><td vAlign='bottom' class='slideBlendTop' style='border:1px solid; border-color:#000000; border-bottom:0px solid;' onMouseOver="this.className='slideBlendTopOut'" onMouseOut="this.className='slideBlendTop'"><center><img src='images/epa_logo.png'></center></td></tr></table></center></td><td width=1 style='border-left:1px solid; border-left-color:#000000;'><div align='left'><img src='images/sideTop.jpg' height='54'></div></td></tr></table></center></td></tr><tr><td width=6><div align='center'><img src='images/led_red.png' width=6 height=23></div></td><td class='fontClass8' align='center' style='background:#FADEDB; color:#336699; border:1px solid; border-left:0px solid; border-color:#424242; padding:0px 2px;' height=10>EPA&nbsp;Return&nbsp;Management</td>
</tr><tr><td></td><td vAlign='top'><center><table width='66' height='7' cellpadding=0 cellspacing=0 border=0><tr><td class='slideBlendTop' style='border:1px solid; border-color:#000000; border-top:0px solid;'><center><img src='images/blank.gif' width=1 height=7></center></td>
</tr><tr><td vAlign='top'><center><img src='images/bottomR.jpg'></center></td></tr></table></center></td></tr></table></center></td></table></center></td></tr><tr><td colSpan=10 vAlign='top'><div align='left'><table width='100%' cellpadding=0 cellspacing=0 border=0><tr><td><div align='left'><table width='100%' cellpadding=0 cellspacing=0 border=0 height=27 style='background:#336699; border:2px solid; border-right:0px solid; border-color:#000000;'><tr><td><center><img src='images/blank.gif' width=24 height=1></center><center><img src='images/blue.jpg' style='border:1px solid; border-color:#FFFFFF;'></center><center><img src='images/blank.gif' width=24 height=1></center></td><td  width='100%' class='fontClass12' align='center' style='color:#FFFFFF;'>SHIPPING</td></tr></table></div></td><td vAlign='top' width=1 style='background:#336699; border-bottom:2px solid; border-bottom-color:#000000;'><div align='left'><img src='images/topCurl2.jpg'></div></td></tr></table></div><center><img src='images/shadow.png' height=29 width=760></center></td></tr><tr><td colSpan=10 style="border:0px dotted; border-color:#424242;" vAlign='top'><div align='left'><table cellpadding=0 cellspacing=0 border=0><tr>
<td onMouseOver="style.cursor='hand';" style="border-left:1px dashed; border-left-color:#FFFFFF; border-bottom:0px solid; border-top:0px solid; border-right:1px dashed; border-right-color:#FFFFFF;" onMouseOver="style.cursor='hand'" onClick="menuChoiceSet(239, 'shipping_stage_labels.php')"><center><table height='76' cellpadding=0 cellspacing=0 border=0 width=150><tr><td></td><td vAlign='bottom'><center><table width='91' height='58' cellpadding=0 cellspacing=0 border=0><tr><td width=1><div align='left'><img src='images/blank.gif' height='1' width='7'></div></td><td width='100%'><center><table width='100%' height='100%' cellpadding=0 cellspacing=0 border=0><tr><td vAlign='bottom' class='slideBlendTop' style='border:1px solid; border-color:#000000; border-bottom:0px solid;' onMouseOver="this.className='slideBlendTopOut'" onMouseOut="this.className='slideBlendTop'"><center><img src='images/shiplabel.png'></center></td></tr></table></center></td><td width=1 style='border-left:1px solid; border-left-color:#000000;'><div align='left'><img src='images/sideTop.jpg' height='54'></div></td></tr></table></center></td></tr><tr><td width=6><div align='center'><img src='images/led_red.png' width=6 height=23></div></td><td class='fontClass8' align='center' style='background:#FADEDB; color:#336699; border:1px solid; border-left:0px solid; border-color:#424242; padding:0px 2px;' height=10>Shipping&nbsp;Label</td>
</tr><tr><td></td><td vAlign='top'><center><table width='66' height='7' cellpadding=0 cellspacing=0 border=0><tr><td class='slideBlendTop' style='border:1px solid; border-color:#000000; border-top:0px solid;'><center><img src='images/blank.gif' width=1 height=7></center></td>
</tr><tr><td vAlign='top'><center><img src='images/bottomR.jpg'></center></td></tr></table></center></td></tr></table></center></td>
<td onMouseOver="style.cursor='hand';" style="border-left:1px dashed; border-left-color:#FFFFFF; border-bottom:0px solid; border-top:0px solid; border-right:1px dashed; border-right-color:#FFFFFF;" onMouseOver="style.cursor='hand'" onClick="menuChoiceSet(249, 'checkUIDNeedOnMSOs.php')"><center><table height='76' cellpadding=0 cellspacing=0 border=0 width=150><tr><td></td><td vAlign='bottom'><center><table width='91' height='58' cellpadding=0 cellspacing=0 border=0><tr><td width=1><div align='left'><img src='images/blank.gif' height='1' width='7'></div></td><td width='100%'><center><table width='100%' height='100%' cellpadding=0 cellspacing=0 border=0><tr><td vAlign='bottom' class='slideBlendTop' style='border:1px solid; border-color:#000000; border-bottom:0px solid;' onMouseOver="this.className='slideBlendTopOut'" onMouseOut="this.className='slideBlendTop'"><center><img src='images/packingsearch.png'></center></td></tr></table></center></td><td width=1 style='border-left:1px solid; border-left-color:#000000;'><div align='left'><img src='images/sideTop.jpg' height='54'></div></td></tr></table></center></td></tr><tr><td width=6><div align='center'><img src='images/led_red.png' width=6 height=23></div></td><td class='fontClass8' align='center' style='background:#FADEDB; color:#336699; border:1px solid; border-left:0px solid; border-color:#424242; padding:0px 2px;' height=10>Packing&nbsp;Search&nbsp;UID</td>
</tr><tr><td></td><td vAlign='top'><center><table width='66' height='7' cellpadding=0 cellspacing=0 border=0><tr><td class='slideBlendTop' style='border:1px solid; border-color:#000000; border-top:0px solid;'><center><img src='images/blank.gif' width=1 height=7></center></td>
</tr><tr><td vAlign='top'><center><img src='images/bottomR.jpg'></center></td></tr></table></center></td></tr></table></center></td></table></center></td></tr>			
	</table></div>
		<center><img src='images/blank.gif' width=1 height=15></center>

	</td>
		</table></div>
</td>
</tr>
</table></div>
<center><img src='images/blank.gif' width=30 height=30></center>
</body>
</html>
