	INCLUDE('INCLUDES/CONNECT.PHP');
				$SQLSTATES = "SELECT *  FROM STATES
								  ORDER BY STATE_NM";
				$QUERYSTATES = MYSQL_QUERY($SQLSTATES,$CON);
			WHILE($ROWSTATES=MYSQL_FETCH_ARRAY($QUERYSTATES))
			{
				IF($FIRSTINITIAL!=SUBSTR(STRTOUPPER($ROWSTATES['STATE_NM']),0,1))
				{
					
					ECHO '<LABEL><B><FONT SIZE="5" >'. SUBSTR(STRTOUPPER($ROWSTATES['STATE_NM']),0,1).'</FONT></B></LABEL>';
				}      
				?>
				  <LABEL><INPUT TYPE="CHECKBOX" NAME="OPTION[]" ID="STATES" VALUE="<? ECHO$ROWSTATES['STATE_ID']?>" /><? ECHO$ROWSTATES['STATE_ABRV']."-".$ROWSTATES['STATE_NM']?></LABEL>
				<?
				
				
					$FIRSTINITIAL=STRTOUPPER(SUBSTR($ROWSTATES['STATE_NM'],0,1));
			}